## AnalyzeBloodwork.R

## SET WORKING DIRECTORY
if (!require("rstudioapi")) {
  install.packages("rstudioapi", dependencies = TRUE)
  library(rstudioapi)
}

setwd(dirname(getActiveDocumentContext()$path))

# INSTALL PACKAGES
## packagelist <- read.csv("Packages.csv", header = FALSE) ?? how to import as a list?.
## resource -  https://statsandr.com/blog/an-efficient-way-to-install-and-load-r-packages/
## resource - https://statisticsglobe.com/r-install-missing-packages-automatically
packagelist <- c("mime", "groupdata2","shiny", "rstudioapi", "dplyr", "tidyr", "knitr", "caret", "ellipse", "ggplot2", "scatterplot3d", "ggvis")
not_installed <- packagelist[!(packagelist %in% installed.packages()[ , "Package"])]    # Extract not installed packages
if(length(not_installed)) install.packages(not_installed)       

# LOAD PACKAGES
invisible(lapply(packagelist, library, character.only = TRUE))

## READ SUBSET LISTS (for dashboard)
WBClist <- c("Monocytes", "Lymphocytes", "Neutrophils", "Basophils", "Eosinophils")
RBClist <- c("RBC", "ESR", "MCH", "HCT")
PlateletList <- c("PlateletCount", "MPV")

## READ DATASETS
IBS1 <- read.csv("../data/RobinsonEtAl_Sup1.csv", header = TRUE)
CBC <- read.csv("../data/WBCsubset.csv", header = TRUE)
IBSblood <- read.csv("../data/CBC_NAomit.csv", header = TRUE)

## DATA PREPARATION - Impute missing values and balance uneven classes (ie. "groups" or "levels") 

## IMPUTE MISSING VALUES USING SAMPLE MEAN
## Resource - https://www.guru99.com/r-replace-missing-values.html

## List columns with NA values
list_na <- colnames(IBSblood)[ apply(IBSblood, 2, anyNA) ]
list_na

## CALCULATE MEAN
## debug - https://stackoverflow.com/questions/28423275/dimx-must-have-a-positive-length-when-applying-function-in-data-frame/28423503
average_missing <- apply(as.matrix(IBSblood[,colnames(IBSblood) %in% list_na]), 
                         2, 
                         mean, 
                         na.rm=TRUE)
average_missing

## REPLACE NA VALUES with the calculated mean
average_missing[1]

IBSblood.replacement <- IBSblood %>%
  mutate(Monocytes = ifelse(is.na(Monocytes), average_missing[1], Monocytes))

sum(is.na(IBSblood.replacement$Monocytes))

## BALANCE CLASSES  using groupdata2 package (ie. New rows are generated by random resampling)
## https://cran.r-project.org/web/packages/groupdata2/vignettes/description_of_groupdata2.html#balance-1
## In the sample data, IBS.subtype levels are unequal and therefore susceptible to inaccurate testing results

## Data as-is
IBSblood %>%
  count(IBS.subtype) %>%
  kable(align = 'c')

## Balance by making each group have 100 rows
df_balanced <- balance(IBSblood.replacement, 100, cat_col = "IBS.subtype") %>% 
  arrange(IBS.subtype, ID)

## Data after balancing
df_balanced %>%
  count(IBS.subtype) %>%
  kable(align = 'c')

## Print out box-whiskers and scatterplot matrix plots for all CBC parameters

# Summarize group proportions
percentage <- prop.table(table(df_balanced$IBS.subtype)) * 100
cbind(freq=table(df_balanced$IBS.subtype), percentage=percentage)


# split input and output
x <- df_balanced[,3:8]
y <- df_balanced[,2]

## Generate box-and-whiskers for each attribute on one image
## how to export?
par(mfrow=c(1,6)) 
for(i in 1:6) {
          boxplot(x[,i], main=names(x)[i])
}

# Export a scatterplot matrix  
## may need an additional package
featurePlot(x=x, y=y, plot="ellipse")

png("../fig_output/ScatterplotMatrix.png")
H1 <- featurePlot(x=x, y=y, plot="ellipse")
print(H1)
dev.off()


## EXPORT HISTOGRAMS FOR ALL PARAMETERS
## Resource - https://stackoverflow.com/questions/49889403/loop-through-dataframe-column-names-r
## Resource - https://statisticsglobe.com/loop-through-data-frame-columns-rows-in-r/
## Resource - https://stackoverflow.com/questions/35372365/how-do-i-generate-a-histogram-for-each-column-of-my-table/35373419
## Resource - https://www.r-bloggers.com/2011/04/automatically-save-your-plots-to-a-folder/

for (col in 2:ncol(CBC)) {
  mypath <- file.path("../fig_output",paste(colnames(CBC[col]),".png",sep = ""))
  png(file=mypath)
  H1 <- hist(CBC[,col], freq=FALSE, main = (colnames(CBC[col])), xlab = (colnames(CBC[col])), breaks=20, col = "lightgreen")
  curve(dnorm(x, mean=mean(CBC[,col], na.rm=TRUE), sd=sd(CBC[,col], na.rm=TRUE)), add=TRUE, col="blue", lwd=2)
  print(H1)
  dev.off()
}

## FIT MULTIPLE REGRESSION for BMI~WBCs
## https://www.statmethods.net/stats/regression.html
## Fit WBC's to BMI 
fit <- lm(BMI ~ Monocytes + Lymphocytes + Neutrophils + Basophils + Eosinophils, data=CBC)
summary(fit) # show results

## EXPORT SCATTERPLOTS for BMI~Lymphocytes
## https://www.statmethods.net/graphs/scatterplot.html
png("../fig_output/BMI_Lymphocytes.png")
H1 <- ggplot(CBC, aes(x=Lymphocytes, y=BMI)) +
  geom_point() +    
  geom_smooth(method=lm)
print(H1)
dev.off()

## EXPORT FIT METRICS PLOTS
png("../fig_output/BMI_CBC_fit.png")
layout(matrix(c(1,2,3,4),2,2))
H1 <- plot(fit)
print(H1)
dev.off()

##  MULTIPLE LINEAR REGRESSIONS with BMI~inflammatory biomarkers
##  https://statquest.org/2017/10/30/statquest-multiple-regression-in-r/
##  http://www.sthda.com/english/articles/40-regression-analysis/167-simple-linear-regression-in-r/
##  http://r-statistics.co/Linear-Regression.html
##  https://www.statmethods.net/stats/regression.html

##  Fit BMI ~ Cortisol, CRP, ESR, PlateletCount, Lymphocyte count.
fit1 <- lm(BMI ~ SerumCortisol + CRP + ESR + PlateletCount + Lymphocytes , data=IBS1)
summary(fit1)

## EXPORT 3D-SCATTERPLOT for (BMI ~ Cortisol + CRP)
## http://www.sthda.com/english/wiki/scatterplot3d-3d-graphics-r-software-and-data-visualization

## Export of this parameter is giving an iss
s3d <- scatterplot3d(IBS1$BMI, IBS1$SerumCortisol, IBS1$CRP,  pch=16, color="steelblue", box=TRUE, highlight.3d=FALSE, type="h", main="BMI x Cortisol x CRP")
fit <- lm(SerumCortisol ~ BMI + CRP, data=IBS1)
s3d$plane3d(fit)


## IDENFITY THE BEST-PERFORMING PREDICTIVE CLASSIFICATION METHOD (MACHINE LEARNING)
## Resource - https://machinelearningmastery.com/machine-learning-in-r-step-by-step/
  
# Run ML classification algorithms using 10-fold cross validation
control <- trainControl(method="cv", number=10)
metric <- "Accuracy"

# a) linear algorithms
set.seed(7)
fit.lda <- train(IBS.subtype~., data=df_balanced, method="lda", metric=metric, trControl=control)
# b) nonlinear algorithms
# CART
set.seed(7)
fit.cart <- train(IBS.subtype~., data=df_balanced, method="rpart", metric=metric, trControl=control)
# kNN
set.seed(7)
fit.knn <- train(IBS.subtype~., data=df_balanced, method="knn", metric=metric, trControl=control)
# c) advanced algorithms
# SVM
set.seed(7)
fit.svm <- train(IBS.subtype~., data=df_balanced, method="svmRadial", metric=metric, trControl=control)
# Random Forest
set.seed(7)
fit.rf <- train(IBS.subtype~., data=df_balanced, method="rf", metric=metric, trControl=control)

# Summarize predictive accuracy of models
results <- resamples(list(lda=fit.lda, cart=fit.cart, knn=fit.knn, svm=fit.svm, rf=fit.rf))
summary(results)

# Export dotplot with model validation
png("../fig_output/ClassificationSelection.png")
H1 <- dotplot(results)
print(H1)
dev.off()

# estimate skill of LDA on the validation dataset
predictions <- predict(fit.rf, df_balanced)
confusionMatrix(predictions, df_balanced$IBS.subtype)

